name: jurassic-application-management-system
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - var _usermenusurl = '/appcenter/functions/getusermenu'
  favicon_hash: []
  priority: 3
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - jurassic
  favicon_hash: []
  priority: 3
  request_method: get
  request_data: ''
  request_headers: {}
