name: oracle-application-server
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - oracle http server</font></font></b></h1>
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - mod_ssl web site
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - oracle jsp documentation
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
- path: /
  status_code: 0
  headers: {}
  keyword:
  - mod_ose documentation
  favicon_hash: []
  priority: 2
  request_method: get
  request_data: ''
  request_headers: {}
