id: application_security_gateway
info:
  name: application_security_gateway
  author: cn-kali-team
  tags: detect,tech,application_security_gateway
  severity: info
  metadata:
    fofa-query:
    - ns-icg
    product: application_security_gateway
    vendor: netentsec
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - ns-icg
