id: blackbox_exporter
info:
  name: blackbox_exporter
  author: cn-kali-team
  tags: detect,tech,blackbox_exporter
  severity: info
  metadata:
    fofa-query:
    - title="blackbox exporter"
    product: blackbox_exporter
    shodan-query:
    - title:"blackbox exporter"
    vendor: prometheus
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>blackbox exporter.*?</title>
