id: ispconfig
info:
  name: ispconfig
  author: cn-kali-team
  tags: detect,tech,ispconfig
  severity: info
  metadata:
    product: ispconfig
    vendor: 00_unknown
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - powered by <a href="http://www.ispconfig.org
    case-insensitive: true
